# Generated by Django 3.1.9 on 2021-12-03 11:32

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('max_x', models.DecimalField(decimal_places=16, max_digits=22)),
                ('max_y', models.DecimalField(decimal_places=16, max_digits=22)),
                ('min_x', models.DecimalField(decimal_places=16, max_digits=22)),
                ('min_y', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
            options={
                'verbose_name': 'BBOX',
                'verbose_name_plural': 'BBOX',
            },
        ),
        migrations.CreateModel(
            name='BBoxImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(upload_to='bbox_img')),
                ('bbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentinel.bbox', verbose_name='BBox')),
            ],
            options={
                'verbose_name': 'Изображения BBOX',
                'verbose_name_plural': 'Изображения BBOX',
            },
        ),
    ]
