# Generated by Django 3.1.9 on 2021-12-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0002_auto_20211203_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbox',
            name='max_x',
            field=models.DecimalField(decimal_places=15, max_digits=22),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='max_y',
            field=models.DecimalField(decimal_places=15, max_digits=22),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='min_x',
            field=models.DecimalField(decimal_places=15, max_digits=22),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='min_y',
            field=models.DecimalField(decimal_places=15, max_digits=22),
        ),
    ]
