# Generated by Django 3.1.9 on 2021-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0003_auto_20211203_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbox',
            name='max_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='max_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='min_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bbox',
            name='min_y',
            field=models.FloatField(),
        ),
    ]
