# Generated by Django 3.1.9 on 2021-12-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0004_auto_20211203_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bboximage',
            options={'ordering': ['-created'], 'verbose_name': 'Изображения BBOX', 'verbose_name_plural': 'Изображения BBOX'},
        ),
        migrations.AddField(
            model_name='bboximage',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bboximage',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
