# Generated by Django 3.1.9 on 2021-12-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilpipline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilpipline',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oilpipline',
            name='geometry',
            field=models.CharField(default='', max_length=50, verbose_name='geometry'),
            preserve_default=False,
        ),
    ]
