# Generated by Django 3.1.9 on 2021-12-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oilpipline', '0002_auto_20211203_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilpipline',
            name='coords',
        ),
        migrations.RemoveField(
            model_name='oilpipline',
            name='geometry',
        ),
    ]
