# Generated by Django 3.1.9 on 2021-12-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilpipline', '0003_auto_20211203_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilpipline',
            name='geo_type',
            field=models.CharField(default='Feature', max_length=50, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='oilpipline',
            name='geometry',
            field=models.JSONField(default=1, verbose_name='geometry'),
            preserve_default=False,
        ),
    ]
