# Generated by Django 3.1.9 on 2021-12-03 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oilpipline', '0004_auto_20211203_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilpipline',
            name='detection',
            field=models.BooleanField(default=False, verbose_name='Детекция'),
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Актуальный')),
                ('geometry', models.JSONField(verbose_name='geometry')),
                ('oli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='oilpipline.oilpipline')),
            ],
        ),
    ]
