# Generated by Django 3.1.9 on 2021-12-03 23:56

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oilpipline', '0006_detection_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['created'], 'verbose_name': 'Детекция', 'verbose_name_plural': 'Детекции обнаружения'},
        ),
        migrations.AddField(
            model_name='detection',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detection',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
