# Generated by Django 3.1.9 on 2021-12-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilpipline', '0007_auto_20211203_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'ordering': ['-created'], 'verbose_name': 'Детекция', 'verbose_name_plural': 'Детекции обнаружения'},
        ),
        migrations.AlterField(
            model_name='detection',
            name='type',
            field=models.CharField(choices=[('warning', 'Предупреждение'), ('danger', 'Опасно'), ('success', 'Успешное обновление'), ('info', 'Запрошены данные')], default='warning', max_length=15, verbose_name='Тип'),
        ),
    ]
